/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-iphone-13-pro-max-4328dea00e47497dbeac73c556121bc9
title: Apple iPhone 13 Pro Max
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/spot.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.00001}>
          <group scale={500}>
            <mesh geometry={nodes.Mesh_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Mesh_1.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Mesh_0001.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Mesh_0002.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Logo_Symbole.geometry} material={materials['Mat.1']} position={[0, -0.07, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
            <mesh geometry={nodes.Logo_Platform.geometry} material={materials.Mat} position={[0, -0.21, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/spot.gltf");