/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-iphone-13-pro-max-4328dea00e47497dbeac73c556121bc9
title: Apple iPhone 13 Pro Max
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

type ModelType = {
  [key: string]: any;
}

export default function Model({ ...props }) {


  const group = React.useRef();

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    group.current.rotation.y = -a*1.5;
  });

  const { nodes, materials }: ModelType = useGLTF("/spot.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0.5, 0]} scale={0.00001}>
          <group scale={500}>
            <mesh geometry={nodes.Mesh_0.geometry} material={materials['Material.003']} color={"green"} />
            <mesh geometry={nodes.Mesh_1.geometry} material={materials['Material.002']} color={"green"} />
            
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/spot.gltf");